version: "3.8"

services:
  uploader:
    build:
      context: .
    volumes:
      - data:/etc/twba/
      - files:/var/tmp/twba/files
    environment:
      - TWBA_CONFIG=/etc/twba/config.toml
#  web:
#    im age: tw

  debug:
    image: debian:stable-slim
    command:
      - /bin/bash
    stdin_open: true
    tty: true
    restart: "no"
    volumes:
      - data:/etc/twba/
      - files:/var/tmp/twba/files
    profiles:
      - no-autostart
volumes:
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/etc/twba/"
  files:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/var/tmp/twba/"